In [1]:
import numpy as np

In [2]:
#simple lists
mylist = [1,2,3,4]

In [3]:
type(mylist)

list

In [5]:
#convert list to array
np.array(mylist)

array([1, 2, 3, 4])

In [6]:
myarray = np.array(mylist)


In [7]:
type(myarray)

numpy.ndarray

In [10]:
#create multi dimensional arrays using range and a step size
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
#create an NxM matrix of zeros
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
#create an NxM matrix of ones
np.ones(shape=(3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#create same random numbers using seed
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [19]:
#create max mean and min of array
arr.max()

95

In [21]:
arr.min()

9

In [22]:
#return index location of max value
arr.argmax()

0

In [23]:
#return index location of min value
arr.argmin()

7

In [24]:
arr.mean()

60.8

In [26]:
#returns a single vector
arr.shape

(10,)

In [27]:
#create 2 rows 5 columns
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [28]:

matt = np.arange(0,100).reshape(10,10)

In [30]:
matt

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
#indexing a value from matt
row = 5
col = 2
mat_index = matt[row,col]

In [32]:
mat_index

52

In [34]:
#slicing out all values in column 5
matt[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [39]:
#reshape into specific array
matt[:,5].reshape(2,5)

array([[ 5, 15, 25, 35, 45],
       [55, 65, 75, 85, 95]])

In [40]:
#slicing out all values in row 5
matt[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [41]:
#reshape into specific array
matt[2,:].reshape(5,2)

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [49]:
#slice out a chunk in the matrix
matt[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [50]:
#copy/duplicate a matrix
mycopy = matt.copy()

In [51]:
mycopy

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
#set values in a matrix to a common value
mycopy[0:6,:] = 88

In [53]:
mycopy

array([[88, 88, 88, 88, 88, 88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88, 88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88, 88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88, 88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88, 88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88, 88, 88, 88, 88, 88],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])